// src/constants/salesQuotes.ts

export const salesQuotes: string[] = [
  "Vender não é sobre convencer, é sobre ajudar.",
  "O 'não' é apenas um degrau para o 'sim'.",
  "Seu sucesso é determinado pelo tamanho da sua persistência.",
  "Clientes compram benefícios, não características.",
  "A melhor hora para fazer uma venda é logo após ter feito uma.",
  "Não encontre clientes para seus produtos, encontre produtos para seus clientes.",
  "Qualidade é o melhor plano de negócios.",
  "O segredo do sucesso em vendas é falar com pessoas.",
  "Vendas curam tudo. Mantenha o funil cheio.",
  "Se você não cuidar do seu cliente, o seu concorrente cuidará.",
  "A venda começa quando o cliente diz não.",
  "Pessoas compram de pessoas em quem confiam.",
  "Entusiasmo é a eletricidade da vida. Como você vende sem ele?",
  "O fracasso é a oportunidade de começar de novo com mais inteligência.",
  "Não diminua a meta, aumente o esforço.",
  "Foque no relacionamento, não apenas na transação.",
  "Cada venda perdida é uma lição aprendida.",
  "O sucesso não acontece por acaso, é trabalho duro.",
  "Seja o especialista que seu cliente precisa.",
  "Vender é transferir confiança.",
  "A objeção é um pedido de mais informação.",
  "Grandes vendedores são grandes ouvintes.",
  "Não venda preço, venda valor.",
  "A motivação é o que te faz começar. O hábito é o que te faz continuar.",
  "Seu sorriso é o seu logotipo, sua personalidade é seu cartão de visitas.",
  "Hoje é um dia perfeito para bater metas.",
  "Crie valor antes de tentar extrair valor.",
  "A persistência realiza o impossível.",
  "Não espere por oportunidades. Crie-as.",
  "Sua atitude determina sua altitude.",
  "O cliente não compra o que você faz, ele compra o porquê você faz.",
  "Toda venda tem cinco obstáculos: falta de necessidade, de dinheiro, de pressa, de desejo ou de confiança.",
  "Faça o cliente se sentir o herói da história.",
  "Vender é a arte de plantar sementes hoje para colher amanhã.",
  "Não prometa o que não pode cumprir. Entregue mais do que prometeu.",
  "A disciplina é a ponte entre metas e realizações.",
  "Quem teme perder já perdeu.",
  "O medo de perder a venda é o maior inimigo do vendedor.",
  "Seja obstinado com a solução do problema do cliente.",
  "Resultados são a única coisa que importa no final do dia.",
  "A sorte favorece a mente preparada.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Conheça seu produto, mas conheça ainda mais seu cliente.",
  "Feito é melhor que perfeito, mas vendas feitas com excelência geram indicações.",
  "Pare de vender. Comece a ajudar.",
  "Sua rede de contatos é seu patrimônio líquido.",
  "Escute 80% do tempo, fale 20%.",
  "Acredite no que você vende ou ninguém acreditará.",
  "Metas claras geram resultados claros.",
  "Você é o único responsável pelo seu sucesso em vendas."
];